name: Storm CMS Event
description: Storm CMS Event
recipes:
  - storm_cms_content_type_base
  - storm_cms_media
  - storm_cms_person
install:
  - datetime_range
  - geolocation_address
  - geolocation_leaflet
  - smart_date
config:
  import:
    smart_date: '*'
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.event:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - event
